spring:
  config:
    import: classpath:application-moodlerules.yml
  jackson:
    default-property-inclusion: non_null
  threads:
    virtual:
      enabled: true

  web:
    resources:
      add-mappings: false

  devtools:
    restart:
      enabled: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  flyway:
    enabled: false

server:
  port: 9090
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: 100MB

springdoc:
  api-docs:
    enabled: false

jwt:
  expiration-time-in-seconds: 7200

moodle:
  api:
    base-url: ${MOODLE_ADAPTER_API_BASE_URL:http://localhost:8080}
    connect-timeout: 5000
    read-timeout: 30000
  db:
    base-path: ./moodle_dbs
logging:
  level:
    org.h2: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG


