INSERT INTO LOGS_ORIGINS (name)
values('web'),
      ('cli'),
      ('ws'),
      ('scheduled'),
      ('restore'),
      ('backup');


INSERT INTO LOGS_COMPONENTS (name)
VALUES ('Activity report'),
       ('Assignment'),
       ('BigBlueButton'),
       ('Book'),
       ('Book printing'),
       ('Chat'),
       ('Choice'),
       ('Database'),
       ('Excel spreadsheet'),
       ('External tool'),
       ('Feedback'),
       ('File'),
       ('File submissions'),
       ('Folder'),
       ('Forum'),
       ('Glossary'),
       ('Grade history'),
       ('Grader report'),
       ('Guía Docente'),
       ('H5P'),
       ('H5P Package'),
       ('Kaltura Video Resource'),
       ('Live logs'),
       ('Logs'),
       ('Online text submissions'),
       ('OpenDocument spreadsheet'),
       ('Overview report'),
       ('Page'),
       ('Question bank'),
       ('Quiz'),
       ('Recycle bin'),
       ('SCORM package'),
       ('SMOWL'),
       ('Single view'),
       ('Submission comments'),
       ('Survey'),
       ('System'),
       ('Tab display'),
       ('URL'),
       ('User report'),
       ('User tours'),
       ('Workshop');

-- Events: 157
INSERT INTO LOGS_EVENTS (name)
VALUES ('A file has been uploaded.'),
       ('A submission has been submitted.'),
       ('All the submissions are being downloaded.'),
       ('An online text has been uploaded.'),
       ('Assignment override created'),
       ('Assignment override deleted'),
       ('Assignment override updated'),
       ('Badge listing viewed'),
       ('Batch set workflow state viewed.'),
       ('Book printed'),
       ('Calendar event created'),
       ('Calendar event deleted'),
       ('Calendar event updated'),
       ('Calendar subscription updated'),
       ('Chapter updated'),
       ('Chapter viewed'),
       ('Choice answer added'),
       ('Choice answer deleted'),
       ('Choice report downloaded'),
       ('Choice report viewed'),
       ('Comment created'),
       ('Comment deleted'),
       ('Content viewed'),
       ('Course activities overview page viewed'),
       ('Course activity completion updated'),
       ('Course backup created'),
       ('Course created'),
       ('Course module created'),
       ('Course module deleted'),
       ('Course module instance list viewed'),
       ('Course module updated'),
       ('Course module viewed'),
       ('Course reset ended'),
       ('Course reset started'),
       ('Course restored'),
       ('Course searched'),
       ('Course section created'),
       ('Course section deleted'),
       ('Course section updated'),
       ('Course summary viewed'),
       ('Course updated'),
       ('Course user report viewed'),
       ('Course viewed'),
       ('Discussion created'),
       ('Discussion deleted'),
       ('Discussion subscription created'),
       ('Discussion viewed'),
       ('Enrolment instance created'),
       ('Enrolment instance updated'),
       ('Entry has been viewed'),
       ('Event created block instance'),
       ('Event deleted block instance'),
       ('Feedback viewed'),
       ('Field created'),
       ('Field updated'),
       ('Folder updated'),
       ('Grade deleted'),
       ('Grade history report viewed'),
       ('Grade item created'),
       ('Grade item deleted'),
       ('Grade item updated'),
       ('Grade overview report viewed'),
       ('Grade single view report viewed.'),
       ('Grade user report viewed'),
       ('Grader report viewed'),
       ('Grading form viewed'),
       ('Grading table viewed'),
       ('Group created'),
       ('Group member added'),
       ('Group member removed'),
       ('Guia docente viewed'),
       ('H5P content viewed'),
       ('Item created'),
       ('Item deleted'),
       ('Live log report viewed'),
       ('Log report viewed'),
       ('OpenDocument grade exported'),
       ('Outline report viewed'),
       ('Page break created'),
       ('Page break deleted'),
       ('Phase switched'),
       ('Post created'),
       ('Post deleted'),
       ('Post updated'),
       ('Question category created'),
       ('Question category deleted'),
       ('Question category updated'),
       ('Question category viewed'),
       ('Question created'),
       ('Question deleted'),
       ('Question manually graded'),
       ('Question moved'),
       ('Question updated'),
       ('Question viewed'),
       ('Questions exported'),
       ('Questions imported'),
       ('Quiz attempt abandoned'),
       ('Quiz attempt auto-saved'),
       ('Quiz attempt deleted'),
       ('Quiz attempt graded'),
       ('Quiz attempt preview started'),
       ('Quiz attempt reviewed'),
       ('Quiz attempt started'),
       ('Quiz attempt submitted'),
       ('Quiz attempt summary viewed'),
       ('Quiz attempt time limit exceeded'),
       ('Quiz attempt updated'),
       ('Quiz attempt viewed'),
       ('Quiz edit page viewed'),
       ('Quiz re-paginated'),
       ('Quiz report viewed'),
       ('Read tracking disabled'),
       ('Read tracking enabled'),
       ('Recent activity viewed'),
       ('Record created'),
       ('Record deleted'),
       ('Record updated'),
       ('Remove submission confirmation viewed.'),
       ('Role assigned'),
       ('Role unassigned'),
       ('Sco launched'),
       ('Section shuffle updated'),
       ('Section viewed'),
       ('Slot created'),
       ('Slot deleted'),
       ('Slot mark updated'),
       ('Slot moved'),
       ('Some content has been posted.'),
       ('Step shown'),
       ('Submission confirmation form viewed.'),
       ('Submission created.'),
       ('Submission form viewed.'),
       ('Submission removed.'),
       ('Submission updated.'),
       ('Submitted SCORM status'),
       ('Subscribers viewed'),
       ('Subscription created'),
       ('Tag added to an item'),
       ('Template updated'),
       ('Templates viewed'),
       ('The state of the workflow has been updated.'),
       ('The status of the submission has been updated.'),
       ('The status of the submission has been viewed.'),
       ('The submission has been graded.'),
       ('The user has accepted the statement of the submission.'),
       ('Tour ended'),
       ('Tour reset'),
       ('Tour started'),
       ('User enrolled in course'),
       ('User graded'),
       ('User list viewed'),
       ('User log report viewed'),
       ('User profile viewed'),
       ('User unenrolled from course'),
       ('Video resource viewed'),
       ('XLS grade exported'),
       ('Zip archive of folder downloaded');
